# Performs all releases using a multipart approach
name: release

env:
  PROJECT_NAME: KModLib
  JAVADOC_NAME: kmodlib

# Variant: github, maven+javadoc

# Changes:
# 2023-04-22 - Kneelawk: Added changes & variant comments. Fixed Grab CF File ID task name. Renamed build job to
#                        build-release. Reformatted.
# 2023-04-22 - Kneelawk: Fix references to build job to point to build-release job.
# 2023-04-22 - Kneelawk: Copy gradle caches to prevent re-building in publishing jobs.
# 2023-05-02 - Kneelawk: Added javadoc publishing. Added maven job step for getting proper tag version by removing 'v'.
# 2023-05-08 - Kneelawk: Combined maven and javadoc steps.
# 2023-05-10 - Kneelawk: Copy all javadoc directories in the docs directory.
# 2023-05-10 - Kneelawk: Use regular publish gradle task.
# 2023-06-25 - Kneelawk: Capture module build directories.

on:
  push:
    tags:
      # matches things like v0.3.3+1.18.2
      - 'v[0-9]+.[0-9]+.[0-9]+\+[0-9]+.[0-9]+.[0-9]+'
      # matches things like v0.4.0+1.19
      - 'v[0-9]+.[0-9]+.[0-9]+\+[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
        env:
          RELEASE_TAG: ${{ github.ref_name }}
      - name: Capture Build Directory
        uses: actions/upload-artifact@v4
        with:
          name: build-dir
          path: build/
      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelogs/changelog-${{ github.ref_name }}.md
          files: build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      - name: Maven Release
        run: ./gradlew publish -PkneelawkUsername=${{ secrets.MAVEN_USERNAME }} -PkneelawkPassword=${{ secrets.MAVEN_PASSWORD }}
        env:
          RELEASE_TAG: ${{ github.ref_name }}
